package org.softcits.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.softcits.mbg.model.MbgUser;
import org.softcits.mbg.model.MbgUserExample;

public interface MbgUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    int countByExample(MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    int deleteByExample(MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    int insert(MbgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    int insertSelective(MbgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    List<MbgUser> selectByExample(MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    MbgUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") MbgUser record, @Param("example") MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    int updateByExample(@Param("record") MbgUser record, @Param("example") MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    int updateByPrimaryKeySelective(MbgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    int updateByPrimaryKey(MbgUser record);
}