package org.softcits.mbg.model;

public class MbgGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_group.id
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_group.group_name
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_group.id
     *
     * @return the value of tbl_group.id
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_group.id
     *
     * @param id the value for tbl_group.id
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_group.group_name
     *
     * @return the value of tbl_group.group_name
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_group.group_name
     *
     * @param groupName the value for tbl_group.group_name
     *
     * @mbggenerated Fri Sep 08 10:18:30 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }
}